
all: mains

mains: main.o libmyBank.a
	gcc -Wall -g -o mains main.o libmyBank.a
	
libmyBank.a: myBank.o
	ar -rcs libmyBank.a myBank.o

myBank.o: myBank.c myBank.h
	gcc -Wall -g -fPIC -c myBank.c
main.o: main.c myBank.h
	gcc -Wall -g -c main.o


.PHONY: clean all 

clean:
	rm -f *.o *.a mains 
